Django app with endpoint users was created.
VadymDemchenko/robot_dreams_homework pull request #26
Opened 2023-05-10 20:49 UTC by VadymDemchenko

2023-05-11 12:20 UTC, klymenok requested changes

2023-05-11 12:20 UTC, klymenok commented on django-homework/.gitignore
> +db.sqlite3
додайте сюди 
```
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class
```

2023-05-11 12:20 UTC, klymenok commented on django-homework/requirements.txt
додайте сюди необхідні залежності `pip freeze > requirements.txt`

2023-05-13 10:54 UTC, VadymDemchenko commented on django-homework/.gitignore
> +db.sqlite3
додав, дякую за пораду

2023-05-13 10:54 UTC, VadymDemchenko commented on django-homework/requirements.txt
вони там є, просто чомусь не відображаються саме тут. Але якщо натиснути view file то все на місці

2023-05-13 17:27 UTC, klymenok approved these changes

2023-05-15 18:06 UTC, merged